name: irs_notice_tracker
description: IRS Notice Tracker App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  pdf: ^3.10.8
  printing: ^5.11.1
  flutter_typeahead: ^5.2.0
  flutter_speed_dial: ^7.0.0
  intl: ^0.19.0
  dropdown_search: ^6.0.2
  csv: ^5.0.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/poa_master_firestore.json
    - assets/poa_master.csv
