// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMCQA69Vx8ydgteqEnwlbv3WqInxakiZo',
    appId: '1:753188109781:web:14275df1d88b534288915c',
    messagingSenderId: '753188109781',
    projectId: 'irs-notice-tracker',
    authDomain: 'irs-notice-tracker.firebaseapp.com',
    storageBucket: 'irs-notice-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0RPmX6BfnHk8Z3StN23kEn8_SZU0noLA',
    appId: '1:753188109781:android:e778070b35da936e88915c',
    messagingSenderId: '753188109781',
    projectId: 'irs-notice-tracker',
    storageBucket: 'irs-notice-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoP-C4ZNP0HTuPqymlNA9yhQDc09Cui8Y',
    appId: '1:753188109781:ios:50116d5773a63e4888915c',
    messagingSenderId: '753188109781',
    projectId: 'irs-notice-tracker',
    storageBucket: 'irs-notice-tracker.firebasestorage.app',
    iosBundleId: 'com.example.irsNoticeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoP-C4ZNP0HTuPqymlNA9yhQDc09Cui8Y',
    appId: '1:753188109781:ios:50116d5773a63e4888915c',
    messagingSenderId: '753188109781',
    projectId: 'irs-notice-tracker',
    storageBucket: 'irs-notice-tracker.firebasestorage.app',
    iosBundleId: 'com.example.irsNoticeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMCQA69Vx8ydgteqEnwlbv3WqInxakiZo',
    appId: '1:753188109781:web:c11d9cb63dec4b9688915c',
    messagingSenderId: '753188109781',
    projectId: 'irs-notice-tracker',
    authDomain: 'irs-notice-tracker.firebaseapp.com',
    storageBucket: 'irs-notice-tracker.firebasestorage.app',
  );

}